Add install queue & event with basic unittest and disk event sample
raven-os/egg pull request #7
Opened 2019-09-22 23:43 UTC by baillyjamy

I added a Singleton for event queue related to the installation of Raven-OS.

A `Disk` or `Partition` instance can be `managed` or not. If this instance is managed then each action executed will have an impact on the disk. If this instance is not managed then the action will be added to the event queue to be executed later. A surface error management can be performed during an unmanaged action. A deep error management can be executed during a managed action.

The goal is to be able to create an action queue when the user sets up his partitions without directly impacting the hard disk. The queue actions will be executed in the final step.
The queue will also be used to add actions such as installing nest packets.

2019-11-17 17:23 UTC, Arignir requested changes

2019-11-17 17:23 UTC, Arignir commented on egg/install_queue/install_queue.py
> +            self.execAll()
Why using a recursive instead of a loop here?

2019-11-17 17:53 UTC, baillyjamy commented on egg/install_queue/install_queue.py
> +            self.execAll()
No specific reason. I wrote this naturally. It doesn't seem to me that it makes the code more complicated.

2019-11-17 19:00 UTC, Arignir commented on egg/install_queue/install_queue.py
> +            self.execAll()
The probability of stack-overflowing here is minimal so i'll merge this, but usually it's safer to go for a loop (and more readable/natural)

2019-11-26 11:08 UTC, Arignir approved these changes

2019-11-26 11:08 UTC, merged